### ISSUE TITLE
Add DSWx_FloodProduct notebook(s) to this repo.

### ISSUE THREAD

**Issue by jmunroe** [ScienceCore/climaterisk#1]
For content, we are using worked examples from https://github.com/OPERA-Cal-Val/OPERA_Applications

- [x] Confirm these examples (and in particular [DSWx_FloodProduct.ipynb](https://github.com/OPERA-Cal-Val/OPERA_Applications/blob/main/DSWx/Flood/DSWx_FloodProduct.ipynb))  work as expected
- [x] Add github user ids from MetaDocencia team
- [x] Add one (or more) JupyterNotebooks to this repo which cover the workflow from the DSWx_FloodProduct example
- [x] #12

**Comment by jmunroe** [comment]
@PatriLoto , @dhavide , @kvenkman  -- Is there one (or more) notebooks that can be adding to this repo that cover the DSWx_FloodProduct workflow?

I will create the appropriate `nbgitpuller` link once there is a notebook in the repo to point to.

**Comment by kvenkman** [comment]
Hi @jmunroe , I am working on a notebook in the `karthik-devel` branch. I'll write up a PR for this tonight.

**Comment by jmunroe** [comment]
Thanks @kvenkman !
