### ISSUE TITLE
Configure JupyterBook so that there is a nbgitpuller link to automatically open into the showcase.2i2c.cloud  JupyterHub

### ISSUE THREAD

**Issue by jmunroe** [ScienceCore/climaterisk#12]
### sub tasks
- [ ] https://github.com/2i2c-org/community-showcase/issues/75
- [ ]

**Comment by jmunroe** [comment]
This is done in PR #19 . The relevant documentation is:

https://jupyterbook.org/en/stable/interactive/launchbuttons.html

(Note: to make this work fully, we need to add the nbgitpuller to the image environment -- but that's in a different repo)

**Comment by colliand** [comment]
2024-05-09. This has been on the back burner. @jmunroe would like this activated into current sprint.

**Comment by choldgraf** [comment]
Here are the JB docs on this:

https://jupyterbook.org/en/stable/interactive/launchbuttons.html#add-a-launch-on-jupyterhub-button

**Comment by choldgraf** [comment]
Funny enough I opened a PR in the CryoCloud repository to do just this, here's the PR for this in case it helps here

https://github.com/CryoInTheCloud/CryoCloudWebsite/pull/98

**Comment by jmunroe** [comment]
This particular task was completed in Feb. What is missing is an update of the underlying image to include nbgitpuller but that is waiting on other changes to the image environment.  

I am going to close this particular issue and create a new one around the image requirements for ScienceCore:climaterisk
