### ISSUE TITLE
Introduction: Setup

### ISSUE THREAD

**Issue by dhavide** [ScienceCore/climaterisk#31]
Prepare clear instructions for getting started (one or two short notebooks with steps required for users in clear bullet lists). This constitutes maybe about 10-15 minutes of instruction in a live session with an audience (giving time for learners to spin up a cloud machine, etc.).

+ Instructions for logging into showcase.2i2c.cloud
+ Instructions for creating NASA EarthData credentials (if needed)
+ Instructions to configure cloud Jupyter environment with required EarthData credentials

**Comment by dhavide** [comment]
@PatriLoto, I've assigned this task to you initially.

A first PR need not be complicated; simply a Markdown document with relevant bullet items as a high-level overview. This can evolve later to be converted to slides and have a script for the speakers, but start with this for now.

Please try to clean up the existing instructions in [1_Getting_Started_text.md](https://github.com/ScienceCore/climaterisk/blob/main/book/1_Getting_Started_text.md) (ignore the [1_Getting_Started.ipynb](https://github.com/ScienceCore/climaterisk/blob/main/book/1_Getting_Started.ipynb) file; we should likely delete this ipynb file from the repo eventually to avoid confusion).

**Comment by PatriLoto** [comment]
ok, I've made the pull request #45 with the first version of the initial configuration file in spanish. In a few days  I'll add improvements to the initial version as well the version file in english.
