### ISSUE TITLE
Review: Geographic data formats

### ISSUE THREAD

**Issue by dhavide** [ScienceCore/climaterisk#32]
The introductory materials need to include a brief notebook summarising commonly used geographic data formats.
+ Resources like [gisgeography.com](https://gisgeography.com/gis-formats/) or [spatialpost.com](https://www.spatialpost.com/list-common-gis-file-format/) may be useful
+ Important: don't get carried away: emphasise primarily the data formats used within the tutorials (no more than 4 or 5).
+ Emphasise concepts learners will need for the analysis (i.e., properties of raster data vs. vector data, etc.).

In live teaching, this is probably about 5-10 minutes to deliver (depending on audience prior experience).

**Comment by kvenkman** [comment]
I think for the contents of this tutorial, it would be sufficient to cover raster and vector data, in the vein of [this blog post](https://www.geographyrealm.com/geodatabases-explored-vector-and-raster-data/)

[This article](https://www.heavy.ai/technical-glossary/geotiff) provides a good explanation about geotiffs and the metadata contained in the header.

Lastly, I think this is a [good article](https://feed.terramonitor.com/shapefile-vs-geopackage-vs-geojson/) to go over about two prominent vector data formats.

**Comment by kvenkman** [comment]
OPERA DSWx raster data is specified as GeoTiffs - covering this data format is a must. For vector data, covering the GeoJSON and SHP file formats will suffice.

**Comment by dhavide** [comment]
As a placeholder: we need to have a discussion about coordinate systems and projections somewhere (so that participants can understand relationships between, e.g., latitude/longitude & easting/northing as they may be extracted from granule metadata or for specifying an AOI.

I don't yet know where this discussion belongs; for now, I think it belongs here in the material on geographic data formats (because coordinates & projection parameters are likely embedded as metadata within geographic data formats).

**Comment by dhavide** [comment]
> OPERA DSWx raster data is specified as GeoTiffs - covering this data format is a must. For vector data, covering the GeoJSON and SHP file formats will suffice.

To make sure that I understand Karthik's answer, in this section of our tutorial, we must cover/explain the basic concepts of:
+ GeoTiffs (raster data)
+ GeoJSON (vector data)
+ SHP (vector data)

For the time being, @marielaraj , work on a brief introduction/explanation of these three data formats in a Markdown file or notebook. Explain in enough detail that someone with minimal familiarity with geospatial data can work out what kind of data is actually pulled down in this tutorial & how to use it.

@kvenkman: in the OPERA application examples that we are currently using in this tutorial, are there any raster data formats *other* than GeoTiffs that we need to explain? If we draw on one of the other OPERA examples, would we conceivably need to explain any other raster format?

**Comment by kvenkman** [comment]
@dhavide Nope, we'll only be using GeoTiffs in this tutorial. We can make a passing mention to cloud-optimized geotiffs ([COGs](https://www.cogeo.org/)), but they won't be used here.
