### ISSUE TITLE
Document workflow for using Jupytext

### ISSUE THREAD

**Issue by dhavide** [ScienceCore/climaterisk#42]
We need to replace all the `.ipynb` files with plain `.py` files (translated through Jupytext). There should also be a `README` and a `.gitignore` so that contributions going forward will have no notebook files for cleaner diffing.

**Comment by kvenkman** [comment]
The issue is partially fixed in [this PR](https://github.com/ScienceCore/climaterisk/pull/46). I'll work on converting all the existing notebooks that don't have corresponding `.py` files and update here.
