### ISSUE TITLE
25/05/24 meeting

### ISSUE THREAD

**Issue by JFormoso** [ScienceCore/climaterisk#53]
Hi everyone!

Here is a list of the actions we defined in today's meeting. If I got anything wrong, please feel free to comment on the issue.

- @JFormoso cleans the structure and the directory. 
- MetaDocencia prepares the slides for the Open Science, Geospatial Fundamentals, and Geospatial Data Files modules. @PatriLoto @marielaraj @JFormoso 
- @jmunroe  will set a one-time password for the 2i2c hub and explain it to @PatriLoto  so she can incorporate it into the getting_started.md notebook.
- MetaDocencia will create a form to evaluate how useful the participants find the tutorial and what we can do to improve the materials. @PatriLoto @marielaraj @JFormoso 
- @kvenkman and @dhavide will generate and document the notebooks for the rest of the modules and put together the activities for the participants.

Best regards!

**Comment by dhavide** [comment]
Thank you @JFormoso for the summary.

I've expanded on the task for you in issue #59 . I'm working on the others while reviewing PRs.
