### ISSUE TITLE
Redundant notebooks?

### ISSUE THREAD

**Issue by kvenkman** [ScienceCore/climaterisk#69]
We should review if the notebooks [SLIDES-NASA-TOPS-flood-EN.ipynb](https://github.com/ScienceCore/climaterisk/blob/main/book/SLIDES-NASA-TOPS-flood-EN.ipynb) and [SLIDES-NASA-TOPS-flood-ES.ipynb](https://github.com/ScienceCore/climaterisk/blob/main/book/SLIDES-NASA-TOPS-flood-ES.ipynb) are still needed - and remove them if not. 

Otherwise, I think the content in there looks great - it needs refining and various section headings need to point to the right place. They can be converted to scripts using jupytext and committed to the repo, I've started a PR here #68

**Comment by JFormoso** [comment]
I think these notebooks are redundant and not needed in the current format. Let me know if I am correct.
