### ISSUE TITLE
Easy log in to 2i2c hub for Scipy tutorial

### ISSUE THREAD

**Issue by PatriLoto** [ScienceCore/climaterisk#71]
Hi @jmunroe. What are the options to facilitate the login to the 2i2c hub to the Scipy tutorial attendees. So as to avoid asking everyone for their Github account. Maybe @jnywong can help on this?

**Comment by jmunroe** [comment]
@jnywong and I briefly discussed this morning.  I see a couple of options:

- letting anyone with a GitHub account access
- setting up a single, common password that is shared by the tutorial presenters at the start of the tutorial 
- using a DummyAuthenticator (any user id /password combination is automatically accepted)

For SciPy I think the dummy authenticator is the simplest. It is a one line configuration change that 2i2c can make the day of the tutorial.

**Comment by jnywong** [comment]
I think it would be worthwhile to test out the dummy authenticator before the day of the tutorial so that instructors know what to expect and how to communicate what to do to the learners.

**Comment by PatriLoto** [comment]
If you think the easiest way to log in to the 2i2c hub is the dummy authenticator, then let's go ahead with that option. I agree with Jenny that it needs to be tested before the tutorial. Moreover, the sooner this option is tested and available the better because it will be necessary to add these steps to the initial configuration guide I have been developing. And this guide should be sent to the attendees a few days before the tutorial.

**Comment by PatriLoto** [comment]
Hi @jmunroe and @jnywong, what are your thoughts about this? Please let me know if it is possible to generate and test the dummy authenticator next week. So I can move forward with updating the initial setup guide. Thanks you!

**Comment by jnywong** [comment]
Hi @PatriLoto , I can take a look this week and will let you know when you can test

**Comment by PatriLoto** [comment]
Perfect! Thank you!

**Comment by PatriLoto** [comment]
Hello @jnywong. I would like to know if there is any news on that. Thanks in advance! 😊

**Comment by jmunroe** [comment]
Internal to 2i2c, we will follow https://infrastructure.2i2c.org/hub-deployment-guide/configure-auth/shared-password/ to make the change.

The effect is when users log in they use any username they like and a "shared password" that is known by the instructors and shared in person.

I will create some screen shots of the expected workflow.

**Comment by PatriLoto** [comment]
Thank you so much, James!

**Comment by jmunroe** [comment]
Here's the url: https://climaterisk.opensci.2i2c.cloud/

You should be able to log with *any* username and the "well-known-shared-password":

![image](https://github.com/ScienceCore/climaterisk/assets/6181563/61382dfd-b03d-4611-b327-a9f109afc2a4)

Files will persist if the same username is used (recommendation: use you GitHub username to avoid name collisions)

Logging in (may take a few minutes if a new node needs to be created)

![image](https://github.com/ScienceCore/climaterisk/assets/6181563/dfe4ecc7-99ef-459d-9273-dfbd622ed13d)

Get user to their own JupyterLab page:

![image](https://github.com/ScienceCore/climaterisk/assets/6181563/96497b61-b86f-4ec0-8d9d-a79fa9a3d447)

[ My next steps are are change the image environment and set it up so that a GitHub repo is automatically cloned with the needed notebooks when a user logs into this hub. ]

I'll will delete any files on this hub after the SciPy tutorial is over.

**Comment by jmunroe** [comment]
I've switched to an image which is built using the `environment.yml` file in this repo.  If a change is made to this `environment.yml`, please flag me at @jmunroe to ensure https://climaterisk.opensci.2i2c.cloud points to the new image.

By default, logging into https://climaterisk.opensci.2i2c.cloud will automatically clone https://github.com/ScienceCore/climaterisk and change to that directly. (upon restart of the jupyter server, this repo is pulled again).

I can also set it so an initial notebook is opened on start up.

@dhavide when you create a new repo for the Scipy2024 material, please flag me at @jmunroe and I will change to cloning that repo instead.

**Comment by dhavide** [comment]
1. I've created a [repository for the SciPy tutorial](https://github.com/ScienceCore/scipy-2024-climaterisk). It is currently a bit bare; we'll add some notebooks shortly, but it at least should be cloneable.
2. The default `notebook` environment in [`climaterisk.opensci.2i2c.cloud`](https://climaterisk.opensci.2i2c.cloud/) is currently giving us problems (import errors for, e.g., `rasterio`). I created a test environment with a later Python version and things worked more smoothly.

@jmunroe, could you please restart `climaterisk.opensci.2i2c.cloud` using the `environment.yml` as in the `scipy-2024-climaterisk` repo in its image?

**Comment by dhavide** [comment]
1. I've created a [repository for the SciPy tutorial](https://github.com/ScienceCore/scipy-2024-climaterisk). It is currently a bit bare; we'll add some notebooks shortly, but it at least should be cloneable.
2. The default `notebook` environment in [`climaterisk.opensci.2i2c.cloud`](https://climaterisk.opensci.2i2c.cloud/) is currently giving us problems (import errors for, e.g., `rasterio`). I created a test environment with a later Python version and things worked more smoothly.

@jmunroe, could you please restart `climaterisk.opensci.2i2c.cloud` using the `environment.yml` as in the `scipy-2024-climaterisk` repo in its image?

**Comment by jnywong** [comment]
@dhavide, concerning your issues with the software environment, I don't see any material differences with your new `scipy-2024-climaterisk/environment.yml` compared with the old `climaterisk/environment.yml`, apart from pinning the version of Python to 3.12.

I am unsure whether your new `scipy-2024-climaterisk/environment.yml` file actually resolves the `rasterio` error you reported. Can you either provide more detail here or upload a test notebook for the SciPy tutorial that I can test the software environment against, even if it's WIP?

Thanks!

**Comment by dhavide** [comment]
> @dhavide, concerning your issues with the software environment, I don't see any material differences with your new `scipy-2024-climaterisk/environment.yml` compared with the old `climaterisk/environment.yml`, apart from pinning the version of Python to 3.12.
> 
> I am unsure whether your new `scipy-2024-climaterisk/environment.yml` file actually resolves the `rasterio` error you reported. Can you either provide more detail here or upload a test notebook for the SciPy tutorial that I can test the software environment against, even if it's WIP?
> 
> Thanks!

No problem, @jnywong .

It seems that the import errors have been resolved in the new environment (which is what I expected from my previous tests). There are more issues to test with visualization; I'll execute notebooks in the new environment to check.

In the meantime, I'll push Karthik's `.netrc` verification script that does a few programmatic checks.

**Comment by jnywong** [comment]
Great! I am going to mark this particular issue as resolved. Please do open a new issue or ping me on Slack if you run into any technical problems.
