### ISSUE TITLE
Merge of new directory structure failed. 

### ISSUE THREAD

**Issue by JFormoso** [ScienceCore/climaterisk#72]
Hi @jnywong and @dhavide!

I tried merging the changes I made to the directory, but it failed. It may be because a review was needed or because I had to make changes. I am not sure. Karthik is waiting for this so he can commit some changes. This is currently a bottleneck. Could you take a look at it, merge it, or let me know what I have to do? I apologize for my lack of experience with these issues.

**Comment by jnywong** [comment]
Okay! I am in a meeting right now but will be able to look at it in the next 2-3 hours.
