### ISSUE TITLE
Moving 04_NASA_Earthdata higher up

### ISSUE THREAD

**Issue by kvenkman** [ScienceCore/climaterisk#77]
The chapter `book/04_NASA_Earthdata` needs to be presented earlier in the list of materials, as it presents creating Earthdata credentials that is needed for subsequent notebooks

**Comment by PatriLoto** [comment]
In line to this, I think it is better to rename the current folder as 00_Getting Started instead of 04_NASA_Earthdata.

**Comment by dhavide** [comment]
I don't agree that this change is necessary (particularly for novices). I think that we need to make sure that the core geospatial concepts are clear first. These can be demonstrated by small code samples running on local data, if necessary. Once the learners have those concepts established clearly, then we can introduce the EarthData credentials and so forth.

My reason for decoupling these topics is largely to make teaching easier; there are more potential places for learners to get confused if we rush to the EarthData credentials immediately. We want to make sure they have those other fundamentals clear in their mind first before they have to start , e.g., struggling with the `pystac` API or worrying whether there are network issues in the connection to the LP DAAC resources or whether the URLs have changed from "provisional" to the official data products, etc.

@kvenkman, we can test this out at SciPy 2024. I know the audience there will be rather sophisticated, but there are still elementary concepts we'll want to cover before dealing with the issues above.

**Comment by dhavide** [comment]
On reflection, this does make sense. I have made this change in the [`scipy-2024-climaterisk`]() repo. After the tutorial, I'll make a PR to merge those changes back into this repo.
