### ISSUE TITLE
Review and make improvements to the Spanish version of the flood notebook.

### ISSUE THREAD

**Issue by PatriLoto** [ScienceCore/climaterisk#8]
After the meeting with Karthik, I'll review in detail to the Spanish version of the flood notebook, in order to make improvements.

**Comment by PatriLoto** [comment]
After the meeting with Karthik, I'll review in detail to the Spanish version of the flood notebook, in order to make improvements.

**Comment by jmunroe** [comment]
Hi @PatriLoto . How did the meeting with @kvenkman go? Are there revisions required?

**Comment by PatriLoto** [comment]
Hi James, I hope you are having a good day. Sorry for the delay in replying. The meeting was super helpful in understanding the notebook better. 
I was waiting for an updated version of the notebook. I just saw Karthik's PR, so that I will have updates on that today or tomorrow.

**Comment by PatriLoto** [comment]
Ready in the #18
